# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "emissa_donation_app"
client_id = "8e23c89439aa9e2d4bcfd466dbaa2b48"
application_url = "https://amp-radiation-stack-warranties.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,write_orders,read_customers,write_metaobject_definitions,read_metaobjects,write_metaobjects"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://amp-radiation-stack-warranties.trycloudflare.com/auth/callback",
  "https://amp-radiation-stack-warranties.trycloudflare.com/auth/shopify/callback",
  "https://amp-radiation-stack-warranties.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ankit-learning-store.myshopify.com"
