import { updateProductId } from "../model/Controller/store.js";
import Stores from "../model/Stores.js";
import shopify from "../shopify.js";
import fetch from 'node-fetch';

export const addProduct = async (session) => {
    const findShop = await Stores.findOne({ storename: session.shop })
    console.log('adding out', findShop)
    if (findShop?.productId == '') {
        console.log('adding in')
        const header = {
            method: 'POST',
            headers: {
                'X-Shopify-Access-Token': session.accessToken,
                "Content-Type": "application/json",
            },
            body: JSON.stringify(product)
        }
        const url = `https://${session.shop}/admin/api/2023-04/products.json`

        const u = await fetch(url, header)
            .then(res => res.json())
            .then(async (data) => {
                console.log("Product added=>", data.product.id)
                await updateProductId(session.shop, data.product.id);
            })
            .catch((error) => { console.log(error) })

    }

}

export const removeProduct = async (session, id) => {
    await shopify.api.rest.Product.delete({
        session: session,
        id: id,
    });
}



export const product = {
    "product": {
        "title": "Carbon footprint reduction",
        "body_html": "Donation for offsetting the carbon footprint of your order.",
        "vendor": "Emissa",
        "product_type": "Carbon Offset",
        "handle": "carbon-neutral-order",
        "published_scope": "global",
        "tags": "",
        "variants": [
            {
                "title": "Offsets 0.43 kgs of carbon",
                "price": "0.23",
                "sku": "",
                "position": 1,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 0.43 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:30:58-05:00",
                "updated_at": "2023-06-28T14:45:14-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 1.04 kgs of carbon",
                "price": "0.27",
                "sku": "",
                "position": 2,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 1.04 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:06-05:00",
                "updated_at": "2023-06-28T14:45:44-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 1.66 kgs of carbon",
                "price": "0.31",
                "sku": "",
                "position": 3,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 1.66 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:07-05:00",
                "updated_at": "2023-06-28T14:45:52-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 2.28 kgs of carbon",
                "price": "0.35",
                "sku": "",
                "position": 4,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 2.28 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:09-05:00",
                "updated_at": "2023-06-28T14:45:55-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 2.9 kgs of carbon",
                "price": "0.39",
                "sku": "",
                "position": 5,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 2.9 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:12-05:00",
                "updated_at": "2023-06-28T14:45:30-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 3.52 kgs of carbon",
                "price": "0.43",
                "sku": "",
                "position": 6,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 3.52 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:14-05:00",
                "updated_at": "2023-06-28T14:45:52-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 4.14 kgs of carbon",
                "price": "0.47",
                "sku": "",
                "position": 7,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 4.14 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:15-05:00",
                "updated_at": "2023-06-28T14:46:06-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 4.76 kgs of carbon",
                "price": "0.51",
                "sku": "",
                "position": 8,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 4.76 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:15-05:00",
                "updated_at": "2023-06-28T14:45:34-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 5.37 kgs of carbon",
                "price": "0.55",
                "sku": "",
                "position": 9,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 5.37 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:16-05:00",
                "updated_at": "2023-06-28T14:45:37-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 6.2 kgs of carbon",
                "price": "0.60",
                "sku": "",
                "position": 10,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 6.2 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:17-05:00",
                "updated_at": "2023-06-28T14:45:31-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 6.82 kgs of carbon",
                "price": "0.64",
                "sku": "",
                "position": 11,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 6.82 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:19-05:00",
                "updated_at": "2023-06-28T14:45:36-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 7.44 kgs of carbon",
                "price": "0.68",
                "sku": "",
                "position": 12,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 7.44 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:20-05:00",
                "updated_at": "2023-06-28T14:45:28-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 8.05 kgs of carbon",
                "price": "0.72",
                "sku": "",
                "position": 13,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 8.05 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:21-05:00",
                "updated_at": "2023-06-28T14:45:50-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 8.88 kgs of carbon",
                "price": "0.78",
                "sku": "",
                "position": 14,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 8.88 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:22-05:00",
                "updated_at": "2023-06-28T14:45:39-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 9.5 kgs of carbon",
                "price": "0.82",
                "sku": "",
                "position": 15,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 9.5 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:23-05:00",
                "updated_at": "2023-06-28T14:46:27-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 10.12 kgs of carbon",
                "price": "0.86",
                "sku": "",
                "position": 16,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 10.12 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:24-05:00",
                "updated_at": "2023-06-28T14:46:06-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 10.94 kgs of carbon",
                "price": "0.91",
                "sku": "",
                "position": 17,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 10.94 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:25-05:00",
                "updated_at": "2023-06-28T14:45:54-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 11.56 kgs of carbon",
                "price": "0.95",
                "sku": "",
                "position": 18,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 11.56 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:27-05:00",
                "updated_at": "2023-06-28T14:45:20-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 12.18 kgs of carbon",
                "price": "0.99",
                "sku": "",
                "position": 19,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 12.18 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:27-05:00",
                "updated_at": "2023-06-28T14:46:07-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 12.8 kgs of carbon",
                "price": "1.03",
                "sku": "",
                "position": 20,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 12.8 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:28-05:00",
                "updated_at": "2023-06-28T14:46:18-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 13.42 kgs of carbon",
                "price": "1.07",
                "sku": "",
                "position": 21,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 13.42 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:29-05:00",
                "updated_at": "2023-06-28T14:45:32-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 14.24 kgs of carbon",
                "price": "1.13",
                "sku": "",
                "position": 22,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 14.24 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:30-05:00",
                "updated_at": "2023-06-28T14:46:08-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 14.86 kgs of carbon",
                "price": "1.17",
                "sku": "",
                "position": 23,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 14.86 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:31-05:00",
                "updated_at": "2023-06-28T14:46:12-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 15.48 kgs of carbon",
                "price": "1.21",
                "sku": "",
                "position": 24,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 15.48 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:32-05:00",
                "updated_at": "2023-06-28T14:46:11-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 16.1 kgs of carbon",
                "price": "1.25",
                "sku": "",
                "position": 25,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 16.1 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:33-05:00",
                "updated_at": "2023-06-28T14:46:28-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 16.71 kgs of carbon",
                "price": "1.29",
                "sku": "",
                "position": 26,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 16.71 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:34-05:00",
                "updated_at": "2023-06-28T14:46:34-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 17.33 kgs of carbon",
                "price": "1.33",
                "sku": "",
                "position": 27,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 17.33 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:35-05:00",
                "updated_at": "2023-06-28T14:45:59-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 17.95 kgs of carbon",
                "price": "1.37",
                "sku": "",
                "position": 28,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 17.95 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:36-05:00",
                "updated_at": "2023-06-28T14:45:28-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 18.57 kgs of carbon",
                "price": "1.41",
                "sku": "",
                "position": 29,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 18.57 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:37-05:00",
                "updated_at": "2023-06-28T14:45:13-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 19.19 kgs of carbon",
                "price": "1.45",
                "sku": "",
                "position": 30,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 19.19 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:38-05:00",
                "updated_at": "2023-06-28T14:45:27-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 20.01 kgs of carbon",
                "price": "1.50",
                "sku": "",
                "position": 31,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 20.01 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:39-05:00",
                "updated_at": "2023-06-28T14:45:35-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 20.63 kgs of carbon",
                "price": "1.54",
                "sku": "",
                "position": 32,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 20.63 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:41-05:00",
                "updated_at": "2023-06-28T14:46:26-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 21.25 kgs of carbon",
                "price": "1.58",
                "sku": "",
                "position": 33,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 21.25 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:42-05:00",
                "updated_at": "2023-06-28T14:45:51-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 21.87 kgs of carbon",
                "price": "1.62",
                "sku": "",
                "position": 34,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 21.87 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:46-05:00",
                "updated_at": "2023-06-28T14:45:22-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 22.49 kgs of carbon",
                "price": "1.66",
                "sku": "",
                "position": 35,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 22.49 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:48-05:00",
                "updated_at": "2023-06-28T14:45:40-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 23.11 kgs of carbon",
                "price": "1.70",
                "sku": "",
                "position": 36,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 23.11 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:48-05:00",
                "updated_at": "2023-06-28T14:45:16-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 23.72 kgs of carbon",
                "price": "1.74",
                "sku": "",
                "position": 37,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 23.72 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:49-05:00",
                "updated_at": "2023-06-28T14:46:13-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 24.34 kgs of carbon",
                "price": "1.78",
                "sku": "",
                "position": 38,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 24.34 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:31:50-05:00",
                "updated_at": "2023-06-28T14:45:58-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 24.96 kgs of carbon",
                "price": "1.82",
                "sku": "",
                "position": 39,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 24.96 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:47:54-05:00",
                "updated_at": "2023-06-28T14:45:20-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 25.58 kgs of carbon",
                "price": "1.86",
                "sku": "",
                "position": 40,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 25.58 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:47:56-05:00",
                "updated_at": "2023-06-28T14:45:25-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 26.2 kgs of carbon",
                "price": "1.90",
                "sku": "",
                "position": 41,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 26.2 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:47:57-05:00",
                "updated_at": "2023-06-28T14:46:04-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 27.02 kgs of carbon",
                "price": "1.96",
                "sku": "",
                "position": 42,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 27.02 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:47:58-05:00",
                "updated_at": "2023-06-28T14:45:18-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 27.64 kgs of carbon",
                "price": "2.00",
                "sku": "",
                "position": 43,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 27.64 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:00-05:00",
                "updated_at": "2023-06-28T14:46:22-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 28.26 kgs of carbon",
                "price": "2.04",
                "sku": "",
                "position": 44,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 28.26 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:02-05:00",
                "updated_at": "2023-06-28T14:45:49-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 28.88 kgs of carbon",
                "price": "2.08",
                "sku": "",
                "position": 45,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 28.88 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:03-05:00",
                "updated_at": "2023-06-28T14:45:56-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 29.5 kgs of carbon",
                "price": "2.12",
                "sku": "",
                "position": 46,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 29.5 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:04-05:00",
                "updated_at": "2023-06-28T14:45:16-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 30.12 kgs of carbon",
                "price": "2.16",
                "sku": "",
                "position": 47,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 30.12 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:05-05:00",
                "updated_at": "2023-06-28T14:46:28-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 30.73 kgs of carbon",
                "price": "2.20",
                "sku": "",
                "position": 48,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 30.73 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:06-05:00",
                "updated_at": "2023-06-28T14:45:46-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 31.35 kgs of carbon",
                "price": "2.24",
                "sku": "",
                "position": 49,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 31.35 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:07-05:00",
                "updated_at": "2023-06-28T14:45:23-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 32.18 kgs of carbon",
                "price": "2.29",
                "sku": "",
                "position": 50,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 32.18 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:08-05:00",
                "updated_at": "2023-06-28T14:45:33-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 32.8 kgs of carbon",
                "price": "2.33",
                "sku": "",
                "position": 51,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 32.8 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:09-05:00",
                "updated_at": "2023-06-28T14:46:00-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 33.42 kgs of carbon",
                "price": "2.37",
                "sku": "",
                "position": 52,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 33.42 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:10-05:00",
                "updated_at": "2023-06-28T14:45:42-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 34.03 kgs of carbon",
                "price": "2.41",
                "sku": "",
                "position": 53,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 34.03 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:11-05:00",
                "updated_at": "2023-06-28T14:46:14-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 34.65 kgs of carbon",
                "price": "2.45",
                "sku": "",
                "position": 54,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 34.65 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:12-05:00",
                "updated_at": "2023-06-28T14:45:57-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 35.27 kgs of carbon",
                "price": "2.49",
                "sku": "",
                "position": 55,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 35.27 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:13-05:00",
                "updated_at": "2023-06-28T14:45:38-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 35.89 kgs of carbon",
                "price": "2.53",
                "sku": "",
                "position": 56,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 35.89 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:14-05:00",
                "updated_at": "2023-06-28T14:46:15-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 36.51 kgs of carbon",
                "price": "2.57",
                "sku": "",
                "position": 57,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 36.51 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:15-05:00",
                "updated_at": "2023-06-28T14:45:49-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 37.13 kgs of carbon",
                "price": "2.61",
                "sku": "",
                "position": 58,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 37.13 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:16-05:00",
                "updated_at": "2023-06-28T14:45:41-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 37.75 kgs of carbon",
                "price": "2.65",
                "sku": "",
                "position": 59,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 37.75 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:17-05:00",
                "updated_at": "2023-06-28T14:45:13-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 38.36 kgs of carbon",
                "price": "2.69",
                "sku": "",
                "position": 60,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 38.36 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:17-05:00",
                "updated_at": "2023-06-28T14:46:11-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 38.98 kgs of carbon",
                "price": "2.73",
                "sku": "",
                "position": 61,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 38.98 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:18-05:00",
                "updated_at": "2023-07-03T19:54:46-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 39.6 kgs of carbon",
                "price": "2.77",
                "sku": "",
                "position": 62,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 39.6 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:20-05:00",
                "updated_at": "2023-06-28T14:46:05-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 40.22 kgs of carbon",
                "price": "2.81",
                "sku": "",
                "position": 63,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 40.22 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:21-05:00",
                "updated_at": "2023-06-28T14:45:45-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 40.84 kgs of carbon",
                "price": "2.85",
                "sku": "",
                "position": 64,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 40.84 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:22-05:00",
                "updated_at": "2023-06-30T21:44:46-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 41.66 kgs of carbon",
                "price": "2.91",
                "sku": "",
                "position": 65,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 41.66 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:23-05:00",
                "updated_at": "2023-06-28T14:46:34-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 42.28 kgs of carbon",
                "price": "2.95",
                "sku": "",
                "position": 66,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 42.28 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:24-05:00",
                "updated_at": "2023-06-28T14:45:53-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 42.9 kgs of carbon",
                "price": "2.99",
                "sku": "",
                "position": 67,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 42.9 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:24-05:00",
                "updated_at": "2023-06-28T14:46:23-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 43.72 kgs of carbon",
                "price": "3.04",
                "sku": "",
                "position": 68,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 43.72 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:25-05:00",
                "updated_at": "2023-06-28T14:46:19-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 44.34 kgs of carbon",
                "price": "3.08",
                "sku": "",
                "position": 69,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 44.34 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:26-05:00",
                "updated_at": "2023-06-28T14:46:03-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 44.96 kgs of carbon",
                "price": "3.12",
                "sku": "",
                "position": 70,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 44.96 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:27-05:00",
                "updated_at": "2023-06-28T14:45:56-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 45.79 kgs of carbon",
                "price": "3.17",
                "sku": "",
                "position": 71,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 45.79 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:28-05:00",
                "updated_at": "2023-06-28T14:45:19-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 46.4 kgs of carbon",
                "price": "3.21",
                "sku": "",
                "position": 72,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 46.4 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:29-05:00",
                "updated_at": "2023-06-28T14:45:25-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 47.23 kgs of carbon",
                "price": "3.27",
                "sku": "",
                "position": 73,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 47.23 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:30-05:00",
                "updated_at": "2023-06-28T14:45:38-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 47.85 kgs of carbon",
                "price": "3.31",
                "sku": "",
                "position": 74,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 47.85 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:31-05:00",
                "updated_at": "2023-06-28T14:45:15-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 48.47 kgs of carbon",
                "price": "3.35",
                "sku": "",
                "position": 75,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 48.47 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:31-05:00",
                "updated_at": "2023-06-28T14:45:24-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 49.29 kgs of carbon",
                "price": "3.40",
                "sku": "",
                "position": 76,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 49.29 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:32-05:00",
                "updated_at": "2023-06-28T14:46:03-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 49.91 kgs of carbon",
                "price": "3.44",
                "sku": "",
                "position": 77,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 49.91 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:33-05:00",
                "updated_at": "2023-06-28T14:45:42-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 50.53 kgs of carbon",
                "price": "3.48",
                "sku": "",
                "position": 78,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 50.53 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:34-05:00",
                "updated_at": "2023-06-28T14:45:43-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 51.35 kgs of carbon",
                "price": "3.54",
                "sku": "",
                "position": 79,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 51.35 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:35-05:00",
                "updated_at": "2023-06-28T14:46:29-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 51.97 kgs of carbon",
                "price": "3.58",
                "sku": "",
                "position": 80,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 51.97 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:36-05:00",
                "updated_at": "2023-06-28T14:46:30-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 71.55 kgs of carbon",
                "price": "3.62",
                "sku": "",
                "position": 81,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 71.55 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:37-05:00",
                "updated_at": "2023-06-28T14:45:35-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 72.37 kgs of carbon",
                "price": "3.66",
                "sku": "",
                "position": 82,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 72.37 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:38-05:00",
                "updated_at": "2023-06-28T14:45:23-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 74.02 kgs of carbon",
                "price": "3.74",
                "sku": "",
                "position": 83,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 74.02 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:39-05:00",
                "updated_at": "2023-06-28T14:46:21-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 76.49 kgs of carbon",
                "price": "3.86",
                "sku": "",
                "position": 84,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 76.49 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:40-05:00",
                "updated_at": "2023-06-28T14:45:47-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 80.62 kgs of carbon",
                "price": "4.06",
                "sku": "",
                "position": 85,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 80.62 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:41-05:00",
                "updated_at": "2023-06-30T11:04:50-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 87.22 kgs of carbon",
                "price": "4.38",
                "sku": "",
                "position": 86,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 87.22 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:42-05:00",
                "updated_at": "2023-06-28T14:45:45-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 97.94 kgs of carbon",
                "price": "4.90",
                "sku": "",
                "position": 87,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 97.94 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:43-05:00",
                "updated_at": "2023-06-30T13:42:42-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 115.26 kgs of carbon",
                "price": "5.74",
                "sku": "",
                "position": 88,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 115.26 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:44-05:00",
                "updated_at": "2023-07-01T11:36:40-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 143.3 kgs of carbon",
                "price": "7.10",
                "sku": "",
                "position": 89,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 143.3 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:45-05:00",
                "updated_at": "2023-06-28T14:46:13-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 188.66 kgs of carbon",
                "price": "9.30",
                "sku": "",
                "position": 90,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 188.66 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:46-05:00",
                "updated_at": "2023-06-28T14:46:31-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 262.06 kgs of carbon",
                "price": "12.86",
                "sku": "",
                "position": 91,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 262.06 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:46-05:00",
                "updated_at": "2023-06-28T14:45:29-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 380.82 kgs of carbon",
                "price": "18.62",
                "sku": "",
                "position": 92,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 380.82 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:47-05:00",
                "updated_at": "2023-06-28T14:45:47-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 572.99 kgs of carbon",
                "price": "27.94",
                "sku": "",
                "position": 93,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 572.99 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:49-05:00",
                "updated_at": "2023-06-28T14:45:26-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 883.92 kgs of carbon",
                "price": "43.02",
                "sku": "",
                "position": 94,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 883.92 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:49-05:00",
                "updated_at": "2023-06-28T14:45:21-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 1387.01 kgs of carbon",
                "price": "67.42",
                "sku": "",
                "position": 95,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 1387.01 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:50-05:00",
                "updated_at": "2023-06-28T14:45:17-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 2201.03 kgs of carbon",
                "price": "106.90",
                "sku": "",
                "position": 96,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 2201.03 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:51-05:00",
                "updated_at": "2023-06-28T14:46:15-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 3518.14 kgs of carbon",
                "price": "170.78",
                "sku": "",
                "position": 97,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 3518.14 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:53-05:00",
                "updated_at": "2023-06-28T14:45:18-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 5649.28 kgs of carbon",
                "price": "274.14",
                "sku": "",
                "position": 98,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 5649.28 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:54-05:00",
                "updated_at": "2023-06-28T14:46:26-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 9097.53 kgs of carbon",
                "price": "441.38",
                "sku": "",
                "position": 99,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 9097.53 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:54-05:00",
                "updated_at": "2023-06-28T14:45:30-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            },
            {
                "title": "Offsets 14676.91 kgs of carbon",
                "price": "711.98",
                "sku": "",
                "position": 100,
                "compare_at_price": "",
                "fulfillment_service": "manual",
                "inventory_management": null,
                "option1": "Offsets 14676.91 kgs of carbon",
                "option2": null,
                "option3": null,
                "created_at": "2023-01-12T15:48:55-05:00",
                "updated_at": "2023-06-28T14:45:54-04:00",
                "taxable": true,
                "barcode": null,
                "grams": 0,
                "image_id": null,
                "weight": 0,
                "weight_unit": "kg",
                "requires_shipping": false
            }
        ],
        "options": [
            {
                "name": "Title",
                "position": 1,
                "values": [
                    "Offsets 0.43 kgs of carbon",
                    "Offsets 1.04 kgs of carbon",
                    "Offsets 1.66 kgs of carbon",
                    "Offsets 2.28 kgs of carbon",
                    "Offsets 2.9 kgs of carbon",
                    "Offsets 3.52 kgs of carbon",
                    "Offsets 4.14 kgs of carbon",
                    "Offsets 4.76 kgs of carbon",
                    "Offsets 5.37 kgs of carbon",
                    "Offsets 6.2 kgs of carbon",
                    "Offsets 6.82 kgs of carbon",
                    "Offsets 7.44 kgs of carbon",
                    "Offsets 8.05 kgs of carbon",
                    "Offsets 8.88 kgs of carbon",
                    "Offsets 9.5 kgs of carbon",
                    "Offsets 10.12 kgs of carbon",
                    "Offsets 10.94 kgs of carbon",
                    "Offsets 11.56 kgs of carbon",
                    "Offsets 12.18 kgs of carbon",
                    "Offsets 12.8 kgs of carbon",
                    "Offsets 13.42 kgs of carbon",
                    "Offsets 14.24 kgs of carbon",
                    "Offsets 14.86 kgs of carbon",
                    "Offsets 15.48 kgs of carbon",
                    "Offsets 16.1 kgs of carbon",
                    "Offsets 16.71 kgs of carbon",
                    "Offsets 17.33 kgs of carbon",
                    "Offsets 17.95 kgs of carbon",
                    "Offsets 18.57 kgs of carbon",
                    "Offsets 19.19 kgs of carbon",
                    "Offsets 20.01 kgs of carbon",
                    "Offsets 20.63 kgs of carbon",
                    "Offsets 21.25 kgs of carbon",
                    "Offsets 21.87 kgs of carbon",
                    "Offsets 22.49 kgs of carbon",
                    "Offsets 23.11 kgs of carbon",
                    "Offsets 23.72 kgs of carbon",
                    "Offsets 24.34 kgs of carbon",
                    "Offsets 24.96 kgs of carbon",
                    "Offsets 25.58 kgs of carbon",
                    "Offsets 26.2 kgs of carbon",
                    "Offsets 27.02 kgs of carbon",
                    "Offsets 27.64 kgs of carbon",
                    "Offsets 28.26 kgs of carbon",
                    "Offsets 28.88 kgs of carbon",
                    "Offsets 29.5 kgs of carbon",
                    "Offsets 30.12 kgs of carbon",
                    "Offsets 30.73 kgs of carbon",
                    "Offsets 31.35 kgs of carbon",
                    "Offsets 32.18 kgs of carbon",
                    "Offsets 32.8 kgs of carbon",
                    "Offsets 33.42 kgs of carbon",
                    "Offsets 34.03 kgs of carbon",
                    "Offsets 34.65 kgs of carbon",
                    "Offsets 35.27 kgs of carbon",
                    "Offsets 35.89 kgs of carbon",
                    "Offsets 36.51 kgs of carbon",
                    "Offsets 37.13 kgs of carbon",
                    "Offsets 37.75 kgs of carbon",
                    "Offsets 38.36 kgs of carbon",
                    "Offsets 38.98 kgs of carbon",
                    "Offsets 39.6 kgs of carbon",
                    "Offsets 40.22 kgs of carbon",
                    "Offsets 40.84 kgs of carbon",
                    "Offsets 41.66 kgs of carbon",
                    "Offsets 42.28 kgs of carbon",
                    "Offsets 42.9 kgs of carbon",
                    "Offsets 43.72 kgs of carbon",
                    "Offsets 44.34 kgs of carbon",
                    "Offsets 44.96 kgs of carbon",
                    "Offsets 45.79 kgs of carbon",
                    "Offsets 46.4 kgs of carbon",
                    "Offsets 47.23 kgs of carbon",
                    "Offsets 47.85 kgs of carbon",
                    "Offsets 48.47 kgs of carbon",
                    "Offsets 49.29 kgs of carbon",
                    "Offsets 49.91 kgs of carbon",
                    "Offsets 50.53 kgs of carbon",
                    "Offsets 51.35 kgs of carbon",
                    "Offsets 51.97 kgs of carbon",
                    "Offsets 71.55 kgs of carbon",
                    "Offsets 72.37 kgs of carbon",
                    "Offsets 74.02 kgs of carbon",
                    "Offsets 76.49 kgs of carbon",
                    "Offsets 80.62 kgs of carbon",
                    "Offsets 87.22 kgs of carbon",
                    "Offsets 97.94 kgs of carbon",
                    "Offsets 115.26 kgs of carbon",
                    "Offsets 143.3 kgs of carbon",
                    "Offsets 188.66 kgs of carbon",
                    "Offsets 262.06 kgs of carbon",
                    "Offsets 380.82 kgs of carbon",
                    "Offsets 572.99 kgs of carbon",
                    "Offsets 883.92 kgs of carbon",
                    "Offsets 1387.01 kgs of carbon",
                    "Offsets 2201.03 kgs of carbon",
                    "Offsets 3518.14 kgs of carbon",
                    "Offsets 5649.28 kgs of carbon",
                    "Offsets 9097.53 kgs of carbon",
                    "Offsets 14676.91 kgs of carbon"
                ]
            }
        ],
        "images": [
            {
                "position": 1,
                "created_at": "2023-04-12T10:57:28-04:00",
                "updated_at": "2023-04-12T10:57:28-04:00",
                "alt": null,
                "width": 512,
                "height": 512,
                "src": "https://i.ibb.co/4fdHqG4/de-coeur-ton-sur-ton-logo-t-shirt-lblauw-1.png",
                "variant_ids": []
            }
        ],
        "image": {
            "position": 1,
            "created_at": "2023-04-12T10:57:28-04:00",
            "updated_at": "2023-04-12T10:57:28-04:00",
            "alt": null,
            "width": 512,
            "height": 512,
            "src": "https://i.ibb.co/4fdHqG4/de-coeur-ton-sur-ton-logo-t-shirt-lblauw-1.png",
            "variant_ids": []
        }
    }
}